# Generated by Django 3.0.2 on 2020-01-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SS', 'Segmentación Silábica'), ('ISI', 'Identificación de la sílaba inicial'), ('FSI', 'Identificación de la sílaba final'), ('ISO', 'Omisión de sílaba inicial'), ('FSO', 'Omisión de sílaba final'), ('SI', 'Inversión silábica'), ('IPI', 'Identificación del fonema inicial'), ('FPI', 'Identificación del fonema final'), ('IPO', 'Omisión de fonema inicial'), ('PS', 'Síntesis fonémica')], default='SS', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
    ]
