# Generated by Django 3.0.2 on 2020-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='typeImage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='My image'),
        ),
    ]
