# Generated by Django 3.0.2 on 2020-01-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_typeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='typeImage',
            field=models.ImageField(blank=True, null=True, upload_to='activities/static/images/', verbose_name='Activity Image'),
        ),
    ]
