# Generated by Django 3.0.2 on 2020-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20200113_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='typeImage',
            field=models.ImageField(blank=True, null=True, upload_to='./static/images/', verbose_name='Activity Image'),
        ),
    ]
