# Generated by Django 3.0.2 on 2020-01-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='text',
        ),
        migrations.AddField(
            model_name='reply',
            name='selected',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
